name: jpj_qto
description: JPJ QTO

version: 6.1.18+63

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json:
  http:
  firebase_messaging:

  ## Widgets
  shimmer:
  another_flushbar:
  cupertino_icons:
  flutter_custom_clippers:
  datetime_picker_formfield:
  transparent_image:
  flutter_rating_bar:
  country_code_picker:
  badges:
  qr_flutter:
  qr_code_scanner:
  expandable:
  image_picker:
  image_cropper:
  camera:
  group_radio_button:
  photo_view:

  ## Tools
  intl:
  provider:
  geolocator:
  flutter_geocoder:
  url_launcher:
  map_launcher:
  app_settings:
  path_provider:
  shared_preferences:
  device_info:
  package_info:
  flutter_screenutil:
  flutter_spinkit:
  random_color:
  hive:
  hive_flutter:
  google_fonts:
  json_annotation:
  html_unescape:
  auto_route:
  flutter_form_builder:
  flutter_easyloading:
  flutter_countdown_timer:
  flutter_localizations:
    sdk: flutter
  sentry_flutter:
  form_builder_validators:
  dropdown_search:
  cached_network_image:
  dropdown_button2:
  get_it:
  get:
  flutter_logs:
  dart_des:
  convert:
  flutter_3des:
  crypto:
  dart_3des:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  hive_generator:
  build_runner:
  flutter_launcher_icons:
  flutter_native_splash:
  auto_route_generator:
  flutter_lints:
  
dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android-icon.png"
  image_path_ios: "assets/icon/ios-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf

  # flutter pub run flutter_launcher_icons:main
