name: jpj_qto
description: JPJ QTO

version: 6.1.15+60

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^5.3.6
  http: ^0.13.5
  firebase_messaging: ^14.2.1

  ## Widgets
  shimmer: ^2.0.0
  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.5
  flutter_custom_clippers: ^2.1.0
  datetime_picker_formfield: ^2.0.1
  transparent_image: ^2.0.0
  flutter_rating_bar: ^4.0.1
  country_code_picker: ^2.0.2
  badges: ^3.0.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  expandable: ^5.0.1
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  camera: ^0.10.3
  group_radio_button: ^1.3.0
  photo_view: ^0.14.0

  ## Tools
  intl: ^0.17.0
  provider: ^6.0.5
  geolocator: ^9.0.2
  flutter_geocoder: ^0.2.2-nullsafety
  url_launcher: ^6.1.8
  map_launcher: ^2.4.0
  app_settings: ^4.2.0
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  device_info: ^2.0.3
  package_info: ^2.0.2
  flutter_screenutil: ^5.6.1
  flutter_spinkit: ^5.1.0
  random_color: ^1.0.6-nullsafety
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.1
  json_annotation: ^4.8.0
  html_unescape: ^2.0.0
  auto_route: ^5.0.4
  flutter_form_builder: ^7.7.0
  flutter_easyloading: ^3.0.5
  flutter_countdown_timer: ^4.1.0
  flutter_localizations:
    sdk: flutter
  sentry_flutter: ^6.19.0
  form_builder_validators: ^8.4.0
  dropdown_search: ^5.0.5
  cached_network_image: ^3.2.3
  dropdown_button2: ^1.9.2
  get_it: ^7.2.0
  get:
  flutter_logs:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  auto_route_generator: ^5.0.3

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android-icon.png"
  image_path_ios: "assets/icon/ios-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf

  # flutter pub run flutter_launcher_icons:main
