name: jpj_qto
description: JPJ QTO

version: 0.0.35+35

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^5.3.4 
  http: ^0.13.5 
  firebase_messaging: ^12.0.2 

  ## Widgets
  shimmer: ^2.0.0 
  another_flushbar: ^1.10.29 
  cupertino_icons: ^1.0.5 
  flutter_custom_clippers: ^2.0.0 
  datetime_picker_formfield: ^2.0.1 
  transparent_image: ^2.0.0
  flutter_rating_bar: ^4.0.1 
  country_code_picker: ^2.0.2 
  badges: ^2.0.3 
  qr_flutter: ^4.0.0 
  qr_code_scanner: ^1.0.1 
  expandable: ^5.0.1 
  image_picker: ^0.8.5+3 
  image_cropper: ^3.0.0
  camera: ^0.10.0+1 
  group_radio_button: ^1.2.0 
  photo_view: ^0.14.0 

  ## Tools
  intl: ^0.17.0 
  provider: ^6.0.3 
  geolocator: ^9.0.1 
  flutter_geocoder: ^0.2.2-nullsafety
  url_launcher: ^6.1.5 
  map_launcher: ^2.3.0+1 
  app_settings: ^4.1.8 
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  device_info: ^2.0.3 
  package_info: ^2.0.2
  flutter_screenutil: ^5.5.3+2 
  flutter_spinkit: ^5.1.0 
  random_color: ^1.0.6-nullsafety
  hive: ^2.2.3 
  hive_flutter: ^1.1.0 
  google_fonts: ^3.0.1 
  json_annotation: ^4.6.0
  html_unescape: ^2.0.0 
  auto_route: ^4.2.1 
  flutter_form_builder:
  flutter_easyloading:
  flutter_countdown_timer:
  flutter_localizations:
    sdk: flutter
  sentry_flutter:
  form_builder_validators:
  dropdown_search:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1 
  hive_generator: ^1.1.3 
  build_runner: ^2.2.0 
  flutter_launcher_icons: ^0.10.0 
  flutter_native_splash: ^2.2.7 
  auto_route_generator: ^4.2.1 

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android-icon.png"
  image_path_ios: "assets/icon/ios-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf

  # flutter pub run flutter_launcher_icons:main
