name: jpj_qto
description: JPJ QTO

version: 0.0.21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^5.3.1
  http: ^0.13.3
  firebase_messaging: ^10.0.7

  ## Widgets
  shimmer: ^2.0.0
  another_flushbar: ^1.10.24
  cupertino_icons: ^1.0.3
  flutter_custom_clippers: ^2.0.0
  datetime_picker_formfield: ^2.0.0
  transparent_image: ^2.0.0
  flutter_rating_bar: ^4.0.0
  country_code_picker: ^2.0.2
  badges: ^2.0.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2
  expandable: ^5.0.1
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1
  camera: ^0.9.2+2
  group_radio_button: ^1.1.0
  photo_view: ^0.12.0

  ## Tools
  intl: ^0.17.0
  provider: ^6.0.1
  geolocator: ^7.6.2
  flutter_geocoder: ^0.2.2-nullsafety
  url_launcher: ^6.0.10
  map_launcher: ^2.1.1
  app_settings: ^4.1.1
  path_provider: ^2.0.4
  shared_preferences: ^2.0.7
  device_info: ^2.0.2
  package_info: ^2.0.2
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  random_color: ^1.0.6-nullsafety
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.1
  html_unescape: ^2.0.0
  auto_route: 2.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4
  hive_generator: ^1.1.1
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  auto_route_generator: 2.1.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android-icon.png"
  image_path_ios: "assets/icon/ios-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf

  # flutter pub run flutter_launcher_icons:main
